"""Constants for the ESPSomfy RTS integration."""

DOMAIN = "espsomfy_rts"
MANUFACTURER = "rstrouse"
API_CONTROLLER = "/controller"
API_SHADES = "/shades"
API_GROUPS = "/groups"
API_SHADECOMMAND = "/shadeCommand"
API_GROUPCOMMAND = "/groupCommand"
API_TILTCOMMAND = "/tiltCommand"
API_DISCOVERY = "/discovery"
API_LOGIN = "/login"
EVT_CONTROLLER = "controller"
EVT_SHADESTATE = "shadeState"
EVT_SHADEADDED = "shadeAdded"
EVT_SHADEREMOVED = "shadeRemoved"
EVT_CONNECTED = "connected"
